// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettierConfig from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      '.wrangler/**',
      'node_modules/**',
      'coverage/**',
      'src/storage/sql/schema.ts', // auto-generated by kysely-codegen
      'worker-configuration.d.ts', // auto-generated by `wrangler types`
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  prettierConfig,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'separate-type-imports' },
      ],
    },
  },
  // Portability zones: Workers-specific types allowed only in the entrypoint and deps.
  {
    files: ['src/**/*.ts'],
    ignores: ['src/index.ts', 'src/cg.config.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@cloudflare/workers-types',
              message:
                'Workers-specific types may only be imported from src/index.ts or src/cg.config.ts.',
            },
            // kysely-d1 removed — replaced by internal src/storage/sql/d1-dialect.ts.
          ],
        },
      ],
    },
  },
  // src/core/ is the future @common-grants/contracts package. It must only
  // depend on `zod` and `@common-grants/sdk` — no imports from other `src/**`
  // directories, which would create a cycle and block future extraction.
  {
    files: ['src/core/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../*', '../../*', '../../../*'],
              message:
                'src/core/ may not import from any other src/** directory. It is the future @common-grants/contracts package — it only depends on zod and @common-grants/sdk.',
            },
          ],
        },
      ],
    },
  },
);
